# Cloud Build configuration for Terraform Destroy
#
# WARNING: This will destroy all infrastructure!
#
# Usage:
#   make destroy

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REGION: us-central1
  _STATE_BUCKET: ${STATE_BUCKET}
  _CLUSTER_NAME: midnight-dev
  _IMAGE_NAME: midnight-dev-platform
  _IMAGE_TAG: latest
  _ENVIRONMENT: dev
  _MIN_INSTANCES: "1"
  _MIDNIGHT_NODE_IMAGE: midnightntwrk/midnight-node:latest-main
  _PROOF_SERVER_IMAGE: midnightnetwork/proof-server:latest
  _INDEXER_IMAGE: midnightntwrk/indexer-standalone:latest
  _MACHINE_TYPE: e2-standard-4
  _PERSISTENT_DISK_SIZE_GB: "100"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Clone the repo (since we use --no-source)
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone'
    args: ['clone', 'https://github.com/${_GITHUB_REPO:-$REPO_NAME}', '/workspace']

  # Initialize Terraform
  - name: 'hashicorp/terraform:1.6'
    id: 'tf-init'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init \
          -backend-config="bucket=${_STATE_BUCKET}" \
          -backend-config="prefix=terraform/state"

  # Terraform Destroy
  - name: 'hashicorp/terraform:1.6'
    id: 'tf-destroy'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform destroy -auto-approve \
          -var="project_id=${_PROJECT_ID}" \
          -var="region=${_REGION}" \
          -var="cluster_name=${_CLUSTER_NAME}" \
          -var="environment=${_ENVIRONMENT}" \
          -var="container_image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/midnight-dev/${_IMAGE_NAME}:${_IMAGE_TAG}" \
          -var="min_instances=${_MIN_INSTANCES}" \
          -var="midnight_node_image=${_MIDNIGHT_NODE_IMAGE}" \
          -var="proof_server_image=${_PROOF_SERVER_IMAGE}" \
          -var="indexer_image=${_INDEXER_IMAGE}" \
          -var="machine_type=${_MACHINE_TYPE}" \
          -var="persistent_disk_size_gb=${_PERSISTENT_DISK_SIZE_GB}"
    waitFor: ['tf-init']

timeout: 1200s
