[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_prg = "H2LLvT2tWWPUYvN2hnNK9G6D5k5EppGzanzJFRtdAsdi"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
wallet = "/Users/kunall/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
