# Cloud Build configuration for Terraform State Cleanup
#
# Generic utility to remove resources from Terraform state, with optional
# destruction of actual cloud resources.
#
# Usage:
#   # List all resources in state
#   make state-cleanup
#
#   # Remove resources from state only (resources remain in cloud)
#   make state-cleanup PATTERN="module.midnight_k8s_services"
#
#   # DESTROY resources AND remove from state
#   make state-cleanup PATTERN="module.midnight_k8s_services" DELETE=true

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REGION: us-central1
  _STATE_BUCKET: ${STATE_BUCKET}
  _STATE_PREFIX: terraform/state
  _RESOURCE_PATTERN: ''
  _DRY_RUN: 'false'
  _DELETE: 'false'
  # Variables needed for terraform destroy
  _CLUSTER_NAME: midnight-dev
  _GKE_CLUSTER_NAME: midnight-dev-gke
  _ENVIRONMENT: dev
  _CHAIN_ENVIRONMENT: standalone
  _IMAGE_NAME: midnight-dev-platform
  _IMAGE_TAG: latest
  _MIDNIGHT_NODE_IMAGE: midnightntwrk/midnight-node:0.18.0
  _PROOF_SERVER_IMAGE: midnightnetwork/proof-server:6.1.0-alpha.6
  _INDEXER_IMAGE: midnightntwrk/indexer-standalone:3.0.0-alpha.20
  _INDEXER_SECRET: ''
  _MACHINE_TYPE: e2-standard-4
  _PERSISTENT_DISK_SIZE_GB: '100'
  _CLOUDBUILD_SA_EMAIL: ''

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Initialize Terraform with remote state
  - name: 'hashicorp/terraform:1.14'
    id: 'tf-init'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init \
          -backend-config="bucket=${_STATE_BUCKET}" \
          -backend-config="prefix=${_STATE_PREFIX}"

  # List and optionally remove/destroy resources
  - name: 'hashicorp/terraform:1.14'
    id: 'tf-state-cleanup'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        
        echo "==========================================="
        echo "Terraform State Cleanup Utility"
        echo "==========================================="
        echo ""
        echo "Pattern:  ${_RESOURCE_PATTERN:-<none - list only>}"
        echo "Dry Run:  ${_DRY_RUN}"
        echo "Delete:   ${_DELETE}"
        echo ""
        # Note: workstations.auto.tfvars is auto-loaded by Terraform if present
        
        echo "=== Current Terraform State ==="
        terraform state list || true
        echo ""
        
        # If no pattern provided, just list and exit
        if [ -z "${_RESOURCE_PATTERN}" ]; then
          echo "No pattern provided. Use PATTERN=<pattern> to specify resources."
          exit 0
        fi
        
        # Find matching resources
        echo "=== Resources matching pattern '${_RESOURCE_PATTERN}' ==="
        MATCHING=$(terraform state list | grep -E "${_RESOURCE_PATTERN}" || true)
        
        if [ -z "$$MATCHING" ]; then
          echo "No resources found matching pattern '${_RESOURCE_PATTERN}'"
          exit 0
        fi
        
        echo "$$MATCHING"
        echo ""
        
        # Count matches
        COUNT=$(echo "$$MATCHING" | wc -l)
        echo "Found $$COUNT resource(s) matching pattern."
        echo ""
        
        # Determine action based on flags
        if [ "${_DELETE}" = "true" ]; then
          ACTION="DESTROY"
        else
          ACTION="REMOVE FROM STATE"
        fi
        
        # If dry run, show what would happen and exit
        if [ "${_DRY_RUN}" = "true" ]; then
          echo "=== DRY RUN - No changes will be made ==="
          echo ""
          if [ "${_DELETE}" = "true" ]; then
            echo "Would DESTROY the following resources (and remove from state):"
            echo "$$MATCHING"
            echo ""
            echo "Running terraform plan -destroy to preview..."
            echo ""
            # Build -target arguments for all matching resources
            TARGETS=""
            echo "$$MATCHING" | while read -r resource; do
              if [ -n "$$resource" ]; then
                TARGETS="$$TARGETS -target=\"$$resource\""
              fi
            done
            # Run plan with targets (show what would be destroyed)
            terraform plan -destroy \
              -var="project_id=${_PROJECT_ID}" \
              -var="region=${_REGION}" \
              -var="cluster_name=${_CLUSTER_NAME}" \
              -var="gke_cluster_name=${_GKE_CLUSTER_NAME}" \
              -var="environment=${_ENVIRONMENT}" \
              -var="chain_environment=${_CHAIN_ENVIRONMENT}" \
              -var="container_image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/midnight-images/${_IMAGE_NAME}:${_IMAGE_TAG}" \
              -var="midnight_node_image=${_MIDNIGHT_NODE_IMAGE}" \
              -var="proof_server_image=${_PROOF_SERVER_IMAGE}" \
              -var="indexer_image=${_INDEXER_IMAGE}" \
              -var="indexer_secret=${_INDEXER_SECRET}" \
              -var="machine_type=${_MACHINE_TYPE}" \
              -var="persistent_disk_size_gb=${_PERSISTENT_DISK_SIZE_GB}" \
              -var="cloudbuild_sa_email=${_CLOUDBUILD_SA_EMAIL}" \
              $(echo "$$MATCHING" | while read -r r; do [ -n "$$r" ] && echo "-target=\"$$r\""; done | tr '\n' ' ') \
              || true
          else
            echo "Would remove the following resources from state (resources remain in cloud):"
            echo "$$MATCHING"
          fi
          exit 0
        fi
        
        # Execute the action
        echo "=== Executing: $$ACTION ==="
        echo ""
        
        if [ "${_DELETE}" = "true" ]; then
          # DESTROY: Use terraform destroy -target for each resource
          # This deletes the actual resource AND removes from state
          echo "$$MATCHING" | while read -r resource; do
            if [ -n "$$resource" ]; then
              echo "Destroying: $$resource"
              terraform destroy -auto-approve \
                -var="project_id=${_PROJECT_ID}" \
                -var="region=${_REGION}" \
                -var="cluster_name=${_CLUSTER_NAME}" \
                -var="gke_cluster_name=${_GKE_CLUSTER_NAME}" \
                -var="environment=${_ENVIRONMENT}" \
                -var="chain_environment=${_CHAIN_ENVIRONMENT}" \
                -var="container_image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/midnight-images/${_IMAGE_NAME}:${_IMAGE_TAG}" \
                -var="midnight_node_image=${_MIDNIGHT_NODE_IMAGE}" \
                -var="proof_server_image=${_PROOF_SERVER_IMAGE}" \
                -var="indexer_image=${_INDEXER_IMAGE}" \
                -var="indexer_secret=${_INDEXER_SECRET}" \
                -var="machine_type=${_MACHINE_TYPE}" \
                -var="persistent_disk_size_gb=${_PERSISTENT_DISK_SIZE_GB}" \
                -var="cloudbuild_sa_email=${_CLOUDBUILD_SA_EMAIL}" \
                -target="$$resource" \
                || echo "  Warning: Failed to destroy $$resource"
            fi
          done
        else
          # REMOVE FROM STATE: Just remove from state, leave resources in cloud
          echo "$$MATCHING" | while read -r resource; do
            if [ -n "$$resource" ]; then
              echo "Removing from state: $$resource"
              terraform state rm "$$resource" || echo "  Warning: Failed to remove $$resource"
            fi
          done
        fi
        
        echo ""
        echo "=== Cleanup complete ==="
        echo ""
        echo "=== Remaining state ==="
        terraform state list || true
    waitFor: ['tf-init']

# Increased timeout for destroy operations (10 minutes)
timeout: 600s
