steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'sudoku-proof-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/sudoku-proof-service:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--timeout'
  - '59m50s'
  - '--cpu'
  - '8'
  - '--memory'
  - '32Gi'
