version: '3.8'

services:
  midnight-workstation:
    image: midnight-workstation:latest
    container_name: midnight-local
    # Override entrypoint to use local startup script
    entrypoint: /usr/local/bin/start-local
    ports:
      - "8080:8080"  # Code OSS IDE
      - "8081:8081"  # Proof Server
    environment:
      - MIDNIGHT_ENV=local
    volumes:
      # Mount templates for development
      - ./templates:/opt/templates:ro
      # Optional: Mount a local workspace
      # - ./workspace:/tmp/user-home/workspace
    networks:
      - midnight-net

networks:
  midnight-net:
    driver: bridge