# Production configuration for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  workstation:
    # Production settings
    environment:
      NODE_ENV: production
      DEBUG: "false"
      # Use external proof service in production
      PROOF_SERVICE_URL: ${PROOF_SERVICE_URL:-https://proof-api.midnight.network}
      
    # Production volumes (read-only where appropriate)
    volumes:
      - ./templates:/workspace/templates:ro
      - ./scripts:/opt/scripts:ro
      - workspace_data:/workspace/projects
      - home_data:/root
      - vscode_data:/root/.config/code-server
      
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 8G
          
    # Restart policy
    restart: always
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        
    # Disable privileged mode in production
    privileged: false