#!/bin/bash
#
# Set GCP_PROJECT_ID environment variable for Cloud Workstations
# This runs early to ensure it's available for all processes including Code OSS
#

echo "Setting up GCP project environment..."

# Detect if we're in a GCP environment (Cloud Workstation or GCE)
# Try to fetch from metadata service - if it works, we're in GCP
PROJECT_ID=$(curl -s -f -H "Metadata-Flavor: Google" \
    "http://metadata.google.internal/computeMetadata/v1/project/project-id" 2>/dev/null || true)

if [ -n "$PROJECT_ID" ]; then
    echo "Running in GCP environment (detected via metadata service)"
    echo "Detected GCP Project: $PROJECT_ID"
        
        # Export for current session and all child processes
        export GCP_PROJECT_ID="$PROJECT_ID"
        export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
        
        # CRITICAL: Add to /etc/environment for systemd services and non-login shells
        # This ensures Code OSS and its terminals inherit the variables
        if ! grep -q "^GCP_PROJECT_ID=" /etc/environment 2>/dev/null; then
            echo "GCP_PROJECT_ID=$PROJECT_ID" >> /etc/environment
        fi
        if ! grep -q "^GOOGLE_CLOUD_PROJECT=" /etc/environment 2>/dev/null; then
            echo "GOOGLE_CLOUD_PROJECT=$PROJECT_ID" >> /etc/environment
        fi
        
        # Add to /etc/profile.d for login shells
        cat > /etc/profile.d/01-gcp-project.sh << EOF
#!/bin/bash
# Auto-generated by Cloud Workstations startup
export GCP_PROJECT_ID="$PROJECT_ID"
export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
EOF
        chmod +x /etc/profile.d/01-gcp-project.sh
        
        # IMPORTANT: Add to /etc/bash.bashrc which is sourced by non-login shells
        # This is what Code OSS terminals will source
        
        # First, ensure bash.bashrc exists
        [ ! -f /etc/bash.bashrc ] && touch /etc/bash.bashrc
        
        # Remove any existing entries first to avoid duplicates
        sed -i '/# Auto-configured GCP Project ID/,+2d' /etc/bash.bashrc 2>/dev/null || true
        
        # Add at the VERY TOP of the file to ensure it's always available
        # Create a temporary file with our content first
        {
            echo "# Auto-configured GCP Project ID for Cloud Workstations"
            echo "export GCP_PROJECT_ID=\"$PROJECT_ID\""
            echo "export GOOGLE_CLOUD_PROJECT=\"$PROJECT_ID\""
            echo ""
            cat /etc/bash.bashrc
        } > /etc/bash.bashrc.tmp && mv /etc/bash.bashrc.tmp /etc/bash.bashrc
        
        # For VSCode/Code OSS integrated terminal, also set in default profile
        # Create a profile.d script that will be sourced by bash
        cat > /etc/profile.d/00-gcp-env.sh << EOF
#!/bin/bash
# Ensure GCP environment is always set for all shells
[ -z "\$GCP_PROJECT_ID" ] && export GCP_PROJECT_ID="$PROJECT_ID"
[ -z "\$GOOGLE_CLOUD_PROJECT" ] && export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
EOF
        chmod +x /etc/profile.d/00-gcp-env.sh
        
    echo "✓ GCP project environment configured: $PROJECT_ID"
    echo "  - Added to /etc/environment (systemd services)"
    echo "  - Added to /etc/bash.bashrc (non-login shells)"
    echo "  - Added to /etc/profile.d (login shells)"
else
    echo "Not running in GCP environment (metadata service not accessible)"
    echo "GCP_PROJECT_ID will need to be set manually"
fi