#!/bin/bash
#
# Set GCP_PROJECT_ID environment variable for Cloud Workstations
# This runs early to ensure it's available for all processes
#

echo "Setting up GCP project environment..."

# Only run if we're in a Cloud Workstation environment
if [ -n "$CLOUD_WORKSTATIONS_CONFIG_DIRECTORY" ] || [ -n "$CLOUD_WORKSTATIONS_CLUSTER" ]; then
    # Fetch project ID from metadata service
    PROJECT_ID=$(curl -s -H "Metadata-Flavor: Google" \
        "http://metadata.google.internal/computeMetadata/v1/project/project-id" 2>/dev/null || true)
    
    if [ -n "$PROJECT_ID" ]; then
        echo "Detected GCP Project: $PROJECT_ID"
        
        # Export for current session
        export GCP_PROJECT_ID="$PROJECT_ID"
        export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
        
        # Add to /etc/environment for all sessions (including SSH)
        echo "GCP_PROJECT_ID=$PROJECT_ID" >> /etc/environment
        echo "GOOGLE_CLOUD_PROJECT=$PROJECT_ID" >> /etc/environment
        
        # Also add to /etc/profile.d for shell sessions
        cat > /etc/profile.d/01-gcp-project.sh << EOF
#!/bin/bash
# Auto-generated by Cloud Workstations startup
export GCP_PROJECT_ID="$PROJECT_ID"
export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
EOF
        chmod +x /etc/profile.d/01-gcp-project.sh
        
        echo "✓ GCP project environment configured: $PROJECT_ID"
    else
        echo "Warning: Could not detect GCP project ID from metadata service"
    fi
else
    echo "Not running in Cloud Workstations, skipping GCP project setup"
fi