apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=
  postgres-connection-string: cHNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQG1pZG5pZ2h0LWR1by1taWRuaWdodC1ub2RlLXBvc3RncmVzOjU0MzIvY2V4cGxvcmVy
