version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./defi_admin.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./backend/config/chains.toml:/app/config/chains.toml:ro
    depends_on:
      - redis
    command: python main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  backend-data:
  frontend-data: